In [1]:
import numpy as np

In [2]:
arr = np.array([1,3,4])

In [3]:
arr

array([1, 3, 4])

In [4]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.full((4,6),8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
np.arange(1,90,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89])

In [10]:
np.linspace(1,20,3)

array([ 1. , 10.5, 20. ])

In [12]:
arr = np.array([[10,20,30],[40,50,60]])

In [13]:
arr

array([[10, 20, 30],
       [40, 50, 60]])

In [14]:
print("shape:",arr.shape)
print("size:", arr.size)
print("dimensions:", arr.ndim)
print("data type:", arr.dtype)

shape: (2, 3)
size: 6
dimensions: 2
data type: int64


In [21]:
arr = np.array([[10,20,30],[40,50,60]],dtype=np.float32)
print(arr.dtype)

float32


In [29]:
n = arr.astype("float64")


In [31]:
n.dtype

dtype('float64')

In [36]:
arr.dtype

dtype('float32')

In [37]:
arr.shape

(2, 3)

In [40]:
reshaped = arr.reshape((3,2))

In [41]:
reshaped

array([[10., 20.],
       [30., 40.],
       [50., 60.]], dtype=float32)

In [43]:
arr

array([[10., 20., 30.],
       [40., 50., 60.]], dtype=float32)

In [46]:
arr.flatten()

array([10., 20., 30., 40., 50., 60.], dtype=float32)