In [9]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[11,12,13]])

In [10]:
arr 

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [11]:
flat = arr.flatten()

In [12]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [13]:
flat[5:9]

array([6, 7, 8, 9])

In [14]:
flat[5]

np.int64(6)

In [15]:
flat[::3]

array([ 1,  4,  7, 11])

In [16]:
b = flat[3:7]

In [17]:
b

array([4, 5, 6, 7])

In [18]:
b[2] = 56565


In [19]:
b

array([    4,     5, 56565,     7])

In [20]:
flat

array([    1,     2,     3,     4,     5, 56565,     7,     8,     9,
          11,    12,    13])

In [21]:
arr = np.array([1,2,1,3,4,5,6,7,8,9])

In [22]:
arr[[2,5,7,9]]


array([1, 5, 7, 9])

In [25]:
arr[arr>3]

array([4, 5, 6, 7, 8, 9])