In [8]:
import numpy as np
arr = np.array([[3, 4, 5], [6, 7, 8], [1, 2, 0]])

In [9]:
arr

array([[3, 4, 5],
       [6, 7, 8],
       [1, 2, 0]])

In [10]:
arr.shape

(3, 3)

In [11]:
ada = np.array([1.1, 2.2, 3.3, 4.4])

In [12]:
ada

array([1.1, 2.2, 3.3, 4.4])

In [13]:
x = ada.astype('int64')

In [14]:
x

array([1, 2, 3, 4])

In [15]:
ind = np.array([1, 2, 3, 4, 5, 6])
ind

array([1, 2, 3, 4, 5, 6])

In [16]:
ind[[1,3,5]]

array([2, 4, 6])

In [17]:
change = arr.reshape(1,9)

In [18]:
change

array([[3, 4, 5, 6, 7, 8, 1, 2, 0]])

In [19]:
new = np.array([34, 45, 56, 67, 78, 12, 23, 89])

In [20]:
new

array([34, 45, 56, 67, 78, 12, 23, 89])

In [21]:
new[new > 50]

array([56, 67, 78, 89])

In [22]:
x = np.linspace(0,1,5).reshape(1,5)

In [23]:
x.shape

(1, 5)