In [1]:
import numpy as np

In [2]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [3]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
arr[1]

array([4, 5, 6])

In [6]:
arr[2]

array([7, 8, 9])

In [9]:
np.sum(arr, axis=0)

array([12, 15, 18])

In [10]:
np.sum(arr, axis = 1)

array([ 6, 15, 24])

In [12]:
arr[2][2]

np.int64(9)

In [15]:
arr[1,2]

np.int64(6)

In [22]:
arr[0:2,1:3]

array([[2, 3],
       [5, 6]])

In [26]:
arr3D = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [32]:
arr3D

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [42]:
arr3D[:,1,:]

array([[ 4,  5,  6],
       [10, 11, 12]])

In [45]:
arr3D[[0,1],[0,1]]

array([[ 1,  2,  3],
       [10, 11, 12]])