In [1]:
import numpy as np


In [2]:
arr = np.array([1,2,3,4,5,6,7,8])

In [5]:
arr = arr**2

In [6]:
arr

array([ 1,  4,  9, 16, 25, 36, 49, 64])

In [7]:
arr + 10

array([11, 14, 19, 26, 35, 46, 59, 74])

In [12]:
arr1 = np.array([[1,2,3,],[4,5,6]])
arr2 = np.array([1,2,3])
res = arr1 +arr2
res

array([[2, 4, 6],
       [5, 7, 9]])

In [15]:
data = np.array([[10,20,30],[15,25,35],[20,30,40],[25,35,45],[30,40,50]])
mean = data.mean(axis=0)
std = data.std(axis=0)
normalized_data = (data - mean) / std
normalized_data

array([[-1.41421356, -1.41421356, -1.41421356],
       [-0.70710678, -0.70710678, -0.70710678],
       [ 0.        ,  0.        ,  0.        ],
       [ 0.70710678,  0.70710678,  0.70710678],
       [ 1.41421356,  1.41421356,  1.41421356]])