In [4]:
import numpy as np

In [5]:
arr = np.array([3,5,2,33])

In [6]:
np.mean(arr)

np.float64(10.75)

In [7]:
np.max(arr)

np.int64(33)

In [8]:
np.std(arr)

np.float64(12.891373084353738)

In [9]:
np.var(arr)

np.float64(166.1875)

In [10]:
np.min(arr)

np.int64(2)

In [11]:
np.sum(arr)

np.int64(43)

In [12]:
np.prod(arr)

np.int64(990)

In [13]:
np.median(arr)

np.float64(4.0)

In [15]:
np.argmin(arr)

np.int64(2)

In [16]:
np.argmax(arr)

np.int64(3)

In [17]:
np.corrcoef(arr)

np.float64(1.0)

In [18]:
np.unique(arr)

array([ 2,  3,  5, 33])

In [19]:
np.diff(arr)

array([ 2, -3, 31])

In [20]:
np.cumsum(arr)

array([ 3,  8, 10, 43])

In [26]:
np.linspace(0,10,20)

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [27]:
np.log(arr)

array([1.09861229, 1.60943791, 0.69314718, 3.49650756])

In [28]:
np.exp(arr)

array([2.00855369e+01, 1.48413159e+02, 7.38905610e+00, 2.14643580e+14])

In [29]:
np.percentile(arr,50)

np.float64(4.0)